---
- name: Ensure team exists in org
  hosts: localhost
  gather_facts: false
  vars_files:
    - ./vars/aap.yml
    - ./vars/user.yml
    - ./vars/all.yml
  tasks:
    - name: Team present
      ansible.platform.team:
        name: "{{ team_name }}"
        organization: "{{ org_name }}"
        state: present
        aap_hostname: "{{ aap_hostname }}"
        aap_username: "{{ aap_username }}"
        aap_password: "{{ aap_password }}"
        aap_validate_certs: "{{ aap_validate_certs }}"
