---
- name: Ensure user exists
  hosts: localhost
  gather_facts: false
  vars_files:
    - ./vars/all.yml
  tasks:
    - name: User present
      ansible.platform.user:
        username: "{{ user_username }}"
        email: "{{ user_email }}"
        password: "{{ user_password }}"
        state: present
        aap_hostname: "{{ aap_hostname }}"
        aap_username: "{{ aap_username }}"
        aap_password: "{{ aap_password }}"
        aap_validate_certs: "{{ aap_validate_certs }}"
