---
- name: Assign role to user in org
  hosts: localhost
  gather_facts: false
  vars_files:
    - ./vars/aap.yml
    - ./vars/user.yml
    - ./vars/all.yml
  tasks:
    - name: User gets org role
      ansible.platform.role_user_assignment:
        user: "{{ user_username }}"
        object_ids:
          - "{{ org_name }}"
        role_definition: "{{ role_for_user_in_org }}"
        state: present
        aap_hostname: "{{ aap_hostname }}"
        aap_username: "{{ aap_username }}"
        aap_password: "{{ aap_password }}"
        aap_validate_certs: "{{ aap_validate_certs }}"
