---
- name: Ensure organization exists
  hosts: localhost
  gather_facts: false
  vars_files:
    - ./vars/all.yml
  tasks:
    - name: Organization present
      ansible.platform.organization:
        name: "{{ org_name }}"
        state: present
        aap_hostname: "{{ aap_hostname }}"
        aap_username: "{{ aap_username }}"
        aap_password: "{{ aap_password }}"
        aap_validate_certs: "{{ aap_validate_certs }}"

- name: Ensure team exists in org
  hosts: localhost
  gather_facts: false
  vars_files:
    - ./vars/all.yml
  tasks:
    - name: Team present
      ansible.platform.team:
        name: "{{ team_name }}"
        organization: "{{ org_name }}"
        state: present
        aap_hostname: "{{ aap_hostname }}"
        aap_username: "{{ aap_username }}"
        aap_password: "{{ aap_password }}"
        aap_validate_certs: "{{ aap_validate_certs }}"

- name: Ensure user exists
  hosts: localhost
  gather_facts: false
  vars_files:
    - ./vars/all.yml
  tasks:
    - name: User present
      ansible.platform.user:
        username: "{{ user_username }}"
        email: "{{ user_email }}"
        password: "{{ user_password }}"
        state: present
        aap_hostname: "{{ aap_hostname }}"
        aap_username: "{{ aap_username }}"
        aap_password: "{{ aap_password }}"
        aap_validate_certs: "{{ aap_validate_certs }}"

- name: Ensure custom role definition exists 
  hosts: localhost
  gather_facts: false
  vars_files:
    - ./vars/all.yml
  tasks:
    - name: Custom role present
      ansible.platform.role_definition:
        name: "{{ custom_role_name }}"
        description: "{{ custom_role_description }}"
        content_type: awx.inventory
        permissions:
          - awx.view_inventory
          - awx.change_inventory
        state: present
        aap_hostname: "{{ aap_hostname }}"
        aap_username: "{{ aap_username }}"
        aap_password: "{{ aap_password }}"
        aap_validate_certs: "{{ aap_validate_certs }}"

- name: Assign role to team in org
  hosts: localhost
  gather_facts: false
  vars_files:
    - ./vars/all.yml
  tasks:
    - name: Team gets role in org
      ansible.platform.role_team_assignment:
        team: "{{ team_name }}"
        assignment_objects:
          - name: "{{ org_name }}"
            type: "organizations"
        role_definition: "{{ role_for_team_in_org }}"
        state: present
        aap_hostname: "{{ aap_hostname }}"
        aap_username: "{{ aap_username }}"
        aap_password: "{{ aap_password }}"
        aap_validate_certs: "{{ aap_validate_certs }}"

- name: Assign role to user in org
  hosts: localhost
  gather_facts: false
  vars_files:
    - ./vars/all.yml
  tasks:
    - name: User gets org role
      ansible.platform.role_user_assignment:
        user: "{{ user_username }}"
        object_ids:
          - "{{ org_name }}"
        role_definition: "{{ role_for_user_in_org }}"
        state: present
        aap_hostname: "{{ aap_hostname }}"
        aap_username: "{{ aap_username }}"
        aap_password: "{{ aap_password }}"
        aap_validate_certs: "{{ aap_validate_certs }}"
